### ISSUE TITLE
Scroll vertical

### ISSUE THREAD

**Issue by AlberDeveloper** [Mel0nABC/ImageOrganizer#1]
Tengo una resolución de 1920*1080 y al ver las imágenes de una biblioteca se corta el texto y no puedo verlo completamente.

![image](https://github.com/user-attachments/assets/89de0c47-8dc4-4b5a-8add-d01c30b467d7)

* Añadir scroll vertical.

**Comment by Mel0nABC** [comment]
¡Muchas gracias por el aviso!

Se mejora el responsive horizontal de la información de las imágenes. Se hace que el objeto infoImgBox-container se añada como nuevo nodo en la galería el primero, para que el scroll funcione correctamente con resoluciones menores a ancho*1440px.

Saludos.
